### ISSUE TITLE
Please write a guide to install on HASS.IO

### ISSUE THREAD

**Issue by tomerbs** [lukiffer/haiku#16]
If I just copy the files i get this error in frontend:
![image](https://user-images.githubusercontent.com/33035719/45259690-2e40ab80-b3db-11e8-89e1-7832de001e13.png)

**Comment by lukiffer** [comment]
I haven't had a hass.io instance to test on in a while. I'll work on getting an install guide written up.

The files can't be copied directly (they need to be compiled first) -- sorry, I never updated the docs 😢 

Try this as an interim solution:

- Install [NodeJS](https://nodejs.org/en/download/) if you don't already have it
- Install gulp 4 if you don't already have it `npm i -g gulp@next`
- Run `gulp build` at the root of the repository
- The compiled files will output to `./.tmp/` You should be able to copy them directly from there.

**Comment by tomerbs** [comment]
Hi lukiffer
I tried to compile it with your instructions but it didn't work.
I will appreciate if you can please send me a link to your compiled files?
Thanks

**Comment by KKlitgaard** [comment]
You should try forcing latest Javascript in the frontend section of the config:

frontend:
  javascript_version: latest

Then force fresh browser cache.

**Comment by tomerbs** [comment]
Hi KKlitgaard,
Thanks for your replay, unfortunately it dosen't work, now this is what i see in the frontend:
![image](https://user-images.githubusercontent.com/33035719/46198501-4ee28e00-c315-11e8-81c6-e28f5fc26d14.png)
Do you have another idea?
Thanks

**Comment by lukiffer** [comment]
@tomerbs apologies for the delay in getting around to this. I just finished up a themes feature that I'll be merging today. Should also have time to at least get the compiled files included in a release as well as improving docs.

**Comment by lukiffer** [comment]
Updated the [Alternate Installation](https://github.com/lukiffer/haiku/blob/master/README.md#alternate-installation) instructions and have updated the CI build to start attaching ZIP archives of the compiled files to the releases. You can download the zip and then copy it to your hass.io config directory. Once you've copied the zip, simply run `unzip haiku-0.1.0.zip -d www` (or some equivalent) to extract it into your `www` folder.

I'm going to go ahead and close this issue. If you are still having troubles feel free to reply and I'll re-open it.
